CREATE DATABASE VEHICULOS

USE VEHICULOS

CREATE TABLE PLACA
(
IdPlaca INT IDENTITY,
NumPlaca VARCHAR(6) UNIQUE,
IdUsuarioP INT,
Monto MONEY DEFAULT 0,
CONSTRAINT PK_IdPlaca PRIMARY KEY (IdPlaca),
CONSTRAINT FK_IdUsuario FOREIGN KEY (IdUsuarioP) REFERENCES USUARIOS (IdUsuarioU)
)

CREATE TABLE USUARIOS
(
IdUsuarioU INT IDENTITY,
Usuario VARCHAR (50) UNIQUE,
Clave VARCHAR (30),
Nombre VARCHAR (50),
Apellido VARCHAR (50),
CONSTRAINT PK_IdUsuario PRIMARY KEY (IdUsuarioU),
)


------------STORED PROCEDURES PARA USUARIOS-------------------

	CREATE PROCEDURE AGREGAR_USUARIO
	@USUARIO VARCHAR (50),
	@CLAVE VARCHAR (30),
	@NOMBRE VARCHAR (20),
	@APELLIDO NVARCHAR (20)
	AS
	BEGIN 
	INSERT INTO USUARIOS (Usuario, Clave, Nombre, Apellido) VALUES (@USUARIO, @CLAVE, @NOMBRE, @APELLIDO)
	END


	CREATE PROCEDURE BORRAR_USUARIO
	@IDUSUARIO INT
	AS
	BEGIN
	DELETE
	USUARIOS WHERE IdUsuario=@IDUSUARIO
	END


	CREATE PROCEDURE ACTUALIZAR_USUARIO
	@IDUSUARIO INT,
	@USUARIO VARCHAR (50),
	@CLAVE VARCHAR (20),
	@NOMBRE VARCHAR (20),
	@APELLIDO NVARCHAR (20)
	AS
	BEGIN 
	UPDATE USUARIOS SET Usuario=@USUARIO, Clave=@CLAVE, Nombre=@NOMBRE, Apellido=@APELLIDO
	WHERE IdUsuario=@IDUSUARIO
	END

	EXEC AGREGAR_USUARIO 'fernanda@gmail.com', '123', 'Fernanda', 'Morera'
	EXEC AGREGAR_USUARIO 'pedro@gmail.com', '123', 'Pedro', 'Rodriguez'
	EXEC BORRAR_USUARIO '3'
	EXEC ACTUALIZAR_USUARIO 2, 'pedro@gmail.com', '111', 'Pedro', 'Rodriguez'


	CREATE PROCEDURE VALIDAR_USUARIO
	@USUARIO VARCHAR (50),
	@CLAVE VARCHAR (30)
	AS
	BEGIN
	SELECT Usuario, Clave, Nombre, Apellido FROM USUARIOS WHERE Usuario=@USUARIO AND Clave=@CLAVE
	END

	------------STORED PROCEDURES PARA PLACAS-------------------


	ALTER PROCEDURE AGREGAR_PLACA
	@NUMPLACA VARCHAR (6),
	@IDUSUARIO INT,
	@MONTO MONEY
	AS
	BEGIN 
	INSERT INTO PLACA(NumPlaca, IdUsuarioP, Monto) VALUES (@NUMPLACA, @IDUSUARIO, @MONTO)
	END


	CREATE PROCEDURE BORRAR_PLACA
	@IDPLACA INT
	AS
	BEGIN
	DELETE
	PLACA WHERE IdPlaca=@IDPLACA
	END


	ALTER PROCEDURE ACTUALIZAR_PLACA
	@IDPLACA INT,
	@NUMPLACA VARCHAR (6),
	@IDUSUARIO INT,
	@MONTO MONEY
	AS
	BEGIN 
	UPDATE PLACA SET NumPlaca=@NUMPLACA, IdUsuarioP=@IDUSUARIO, Monto=@MONTO
	WHERE IdPlaca=@IDPLACA
	END

	EXEC AGREGAR_PLACA '123456', '604780410', '50000'
	EXEC BORRAR_PLACA '1'
	EXEC ACTUALIZAR_PLACA 2, '123456', '604780410', '40000'
